/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.revert.schema.version.model;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RSVEntity service. Represents a row in the &quot;RSVEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.revert.schema.version.model.impl.RSVEntityModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.revert.schema.version.model.impl.RSVEntityImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RSVEntity
 * @generated
 */
@ProviderType
public interface RSVEntityModel
	extends BaseModel<RSVEntity>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rsv entity model instance should use the {@link RSVEntity} interface instead.
	 */

	/**
	 * Returns the primary key of this rsv entity.
	 *
	 * @return the primary key of this rsv entity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rsv entity.
	 *
	 * @param primaryKey the primary key of this rsv entity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this rsv entity.
	 *
	 * @return the mvcc version of this rsv entity
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this rsv entity.
	 *
	 * @param mvccVersion the mvcc version of this rsv entity
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the rsv entry ID of this rsv entity.
	 *
	 * @return the rsv entry ID of this rsv entity
	 */
	public long getRsvEntryId();

	/**
	 * Sets the rsv entry ID of this rsv entity.
	 *
	 * @param rsvEntryId the rsv entry ID of this rsv entity
	 */
	public void setRsvEntryId(long rsvEntryId);

	/**
	 * Returns the company ID of this rsv entity.
	 *
	 * @return the company ID of this rsv entity
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this rsv entity.
	 *
	 * @param companyId the company ID of this rsv entity
	 */
	@Override
	public void setCompanyId(long companyId);

}